wireguard-test-y += peerlookup.o
wireguard-test-y += peer.o
wireguard-test-y += cookie.o
wireguard-test-y += queueing.o
wireguard-test-y += timers.o
wireguard-test-y += send.o
wireguard-test-y += receive.o
wireguard-test-y += allowedips.o
wireguard-test-y += device.o
wireguard-test-y += noise.o
wireguard-test-y += netlink.o
wireguard-test-y += socket.o
wireguard-test-y += ratelimiter.o

# Or test-rhashtable.o
wireguard-test-y += test-hashtable.o
obj-m := wireguard-test.o
